function mostrar_ventana(nombre,imagen, descripcion,precio) {
    var ventana = window.open("", "ventana", "width=800 height=300 scrollbars=true");
    ventana.document.open();
    ventana.document.write("<html><head><title>Detalles</title><link href=\"css/estilos_detalles.css\" rel=\"stylesheet\" type=\"text/css\">");
    ventana.document.write("<link href=\"css/header.css\" rel=\"stylesheet\" type=\"text/css\" />");
	ventana.document.write("<link href=\"css/footer.css\" rel=\"stylesheet\" type=\"text/css\" />");
	ventana.document.write("<link href=\"css/estilos_botones.css\" rel=\"stylesheet\" type=\"text/css\" />");
	ventana.document.write("<link href=\"css/estilos_input_text.css\" rel=\"stylesheet\" type=\"text/css\" />");
	ventana.document.write("<script type=\"text/javascript\" src=\"js/js_detalles.js\"></script></head><body>");
    ventana.document.write("</div>");
    ventana.document.write("            <div id=\"imagen\">");
    ventana.document.write("            <h1>"+nombre+"</h1>");
    ventana.document.write("            <div id=\"img_principal\">");
    ventana.document.write("                <img src=\""+imagen+"\" name=\"visorImagen\" id=\"visorImagen\">");
    ventana.document.write("            </div>");
    ventana.document.write("            <div id=\"img_secundarias\">");
    ventana.document.write("                <img class=\"linea_img\" src=\"imagen/foto1.jpg\" name=\"foto1\" id=\"foto1\">");
    ventana.document.write("                <img class=\"linea_img\" src=\"imagen/foto2.jpg\" name=\"foto1\" id=\"foto1\">");
    ventana.document.write("                <img class=\"linea_img\" src=\"imagen/foto3.jpg\" name=\"foto1\" id=\"foto1\">");
    ventana.document.write("                <img class=\"linea_img\" src=\"imagen/foto4.jpg\" name=\"foto1\" id=\"foto1\">");
    ventana.document.write("                <img class=\"linea_img\" src=\"imagen/foto5.jpg\" name=\"foto1\" id=\"foto1\">");
    ventana.document.write("            </div>");
    ventana.document.write("        </div>");        
    ventana.document.write("        <div id=\"info\">");
    ventana.document.write("            <div id=\"descripcion\">");
    ventana.document.write("                <h3>Ficha T&eacute;cnica</h3>");
    ventana.document.write("                <p>"+descripcion+"</p>");
    ventana.document.write("            </div>");
    ventana.document.write("            <div id=\"info_gral\">");
    ventana.document.write("                <form>Disponibilidad: <input type=\"text\" disabled=\"disabled\" value=\"En existencia\" id=\"txt_dispo\"><br>");
    ventana.document.write("                    Cantidad: <input type=\"number\" id=\"txt_cantidad\"><br>");
    ventana.document.write("                    Precio Unitario:<input type=\"text\" disabled=\"disabled\" value=\""+precio+"\" id=\"txt_precio\">MXN<br>");
    ventana.document.write("                    Total: <input type=\"text\" disabled=\"disabled\" id=\"txt_total\">MXN<br>");
    ventana.document.write("                    <a id=\"btn_agregar\" class=\"boton\" value=\"A&ntilde;adir al carrito\" href=\"#\">A&ntilde;adir al carrito</a>");
    ventana.document.write("                </form>");
    ventana.document.write("            </div>");
	ventana.document.write("	      </div>");
    ventana.document.write("</body></html>");
    ventana.document.close();
    ventana.focus();
}